import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, type ReactNode, useContext, useEffect, useMemo, useState } from 'react';

export const languages = [
  { code: 'en', label: 'English' }, { code: 'hi', label: 'हिंदी' }, { code: 'te', label: 'తెలుగు' },
  { code: 'kn', label: 'ಕನ್ನಡ' }, { code: 'ta', label: 'தமிழ்' }, { code: 'mr', label: 'मराठी' },
] as const;
export type LanguageCode = typeof languages[number]['code'];
type Key = keyof typeof copy.en;
const STORAGE_KEY = 'agrinode.language';
const copy = {
  en: { home: 'Home', market: 'Market', scanner: 'Scanner', orders: 'Orders', profile: 'Profile', tracking: 'Tracking', quickActions: 'Quick actions', sellProduce: 'Sell Produce', aiScanner: 'AI Scanner', logistics: 'Logistics', loadPooling: 'Load Pooling', payments: 'Payments', alerts: 'Alerts', viewAll: 'View all', seeAll: 'See all', marketWatchlist: 'Market watchlist', demoPrices: 'Demo prices · refreshed today', marketPrice: 'Market price', currentMandiPrice: 'Current mandi price', previousPrice: 'Previous price', sevenDayTrend: '7-day trend', demand: 'Demand', demoDemand: 'Demo demand indicator', strongBuyerActivity: 'Strong buyer activity', moderateBuyerActivity: 'Moderate buyer activity', limitedBuyerActivity: 'Limited buyer activity', marketSnapshot: 'Market snapshot', sourceDetails: 'Source details', language: 'Language', chooseLanguage: 'Choose your preferred app language', commonBack: 'Back', commonSave: 'Save', high: 'High', medium: 'Medium', low: 'Low' },
  hi: { home: 'होम', market: 'बाज़ार', scanner: 'स्कैनर', orders: 'ऑर्डर', profile: 'प्रोफ़ाइल', tracking: 'ट्रैकिंग', quickActions: 'त्वरित कार्य', sellProduce: 'उपज बेचें', aiScanner: 'AI स्कैनर', logistics: 'लॉजिस्टिक्स', loadPooling: 'लोड पूलिंग', payments: 'भुगतान', alerts: 'सूचनाएँ', viewAll: 'सभी देखें', seeAll: 'सभी देखें', marketWatchlist: 'बाज़ार वॉचलिस्ट', demoPrices: 'डेमो कीमतें · आज ताज़ा की गईं', marketPrice: 'बाज़ार मूल्य', currentMandiPrice: 'वर्तमान मंडी मूल्य', previousPrice: 'पिछली कीमत', sevenDayTrend: '7-दिन रुझान', demand: 'मांग', demoDemand: 'डेमो मांग संकेतक', strongBuyerActivity: 'मजबूत खरीदार गतिविधि', moderateBuyerActivity: 'मध्यम खरीदार गतिविधि', limitedBuyerActivity: 'सीमित खरीदार गतिविधि', marketSnapshot: 'बाज़ार सारांश', sourceDetails: 'स्रोत विवरण', language: 'भाषा', chooseLanguage: 'अपनी पसंदीदा ऐप भाषा चुनें', commonBack: 'वापस', commonSave: 'सहेजें', high: 'उच्च', medium: 'मध्यम', low: 'कम' },
  te: { home: 'హోమ్', market: 'మార్కెట్', scanner: 'స్కానర్', orders: 'ఆర్డర్లు', profile: 'ప్రొఫైల్', tracking: 'ట్రాకింగ్', quickActions: 'త్వరిత చర్యలు', sellProduce: 'పంట అమ్మండి', aiScanner: 'AI స్కానర్', logistics: 'లాజిస్టిక్స్', loadPooling: 'లోడ్ పూలింగ్', payments: 'చెల్లింపులు', alerts: 'అలర్ట్‌లు', viewAll: 'అన్నీ చూడండి', seeAll: 'అన్నీ చూడండి', marketWatchlist: 'మార్కెట్ వాచ్‌లిస్ట్', demoPrices: 'డెమో ధరలు · ఈరోజు నవీకరించబడ్డాయి', marketPrice: 'మార్కెట్ ధర', currentMandiPrice: 'ప్రస్తుత మండీ ధర', previousPrice: 'మునుపటి ధర', sevenDayTrend: '7-రోజుల ధోరణి', demand: 'డిమాండ్', demoDemand: 'డెమో డిమాండ్ సూచిక', strongBuyerActivity: 'బలమైన కొనుగోలుదారు ఆసక్తి', moderateBuyerActivity: 'మధ్యస్థ కొనుగోలుదారు ఆసక్తి', limitedBuyerActivity: 'పరిమిత కొనుగోలుదారు ఆసక్తి', marketSnapshot: 'మార్కెట్ సారాంశం', sourceDetails: 'మూల వివరాలు', language: 'భాష', chooseLanguage: 'మీ యాప్ భాషను ఎంచుకోండి', commonBack: 'వెనుకకు', commonSave: 'సేవ్', high: 'ఎక్కువ', medium: 'మధ్యస్థ', low: 'తక్కువ' },
  kn: {}, ta: {}, mr: {},
} as const;
type I18n = { language: LanguageCode; setLanguage: (language: LanguageCode) => void; t: (key: Key) => string; ready: boolean };
const Context = createContext<I18n | undefined>(undefined);
export function I18nProvider({ children }: { children: ReactNode }) { const [language, setLanguageState] = useState<LanguageCode>('en'); const [ready, setReady] = useState(false); useEffect(() => { AsyncStorage.getItem(STORAGE_KEY).then(value => { if (languages.some(item => item.code === value)) setLanguageState(value as LanguageCode); }).finally(() => setReady(true)); }, []); const setLanguage = (next: LanguageCode) => { setLanguageState(next); AsyncStorage.setItem(STORAGE_KEY, next).catch(() => undefined); }; const value = useMemo(() => ({ language, setLanguage, t: (key: Key) => (copy[language] as Partial<typeof copy.en>)[key] ?? copy.en[key], ready }), [language, ready]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useI18n() { const context = useContext(Context); if (!context) throw new Error('useI18n must be inside I18nProvider'); return context; }
