import { getDemoMarketLocation, getDemoMarketName } from '@/data/marketLocations';
import { marketCommodities } from '@/data/mockData';
import type { MarketDataProvider, MarketPrice } from '@/types/market';
import { calculateChangePercent, normalizePriceToKg } from '@/utils/priceConversion';
import { getApiResponse } from './apiClient';
import type { UserLocation } from './locationService';
const location={district:'Nizamabad',state:'Telangana'};
export class MockMarketDataProvider implements MarketDataProvider { async getPrices():Promise<MarketPrice[]> { return marketCommodities.map((item)=>{const current=normalizePriceToKg(item.sourcePrice,item.sourceUnit);const previous=current/(1+item.changePercent/100);const metadata=getDemoMarketLocation(item.id);const market=getDemoMarketName(item.id)??item.market;return {id:item.id,name:item.name,category:item.category,commodity:item.name,variety:'Grade A',market,district:metadata?.district??location.district,state:metadata?.state??location.state,date:'2026-09-09',sourcePrice:item.sourcePrice,sourceUnit:item.sourceUnit,minPrice:Math.round(item.sourcePrice*.91),maxPrice:Math.round(item.sourcePrice*1.08),modalPrice:item.sourcePrice,normalizedPricePerKg:current,previousPricePerKg:previous,changePercent:calculateChangePercent(current,previous),trend:item.trend,demand:item.demand,source:'Mock',lastUpdated:item.lastUpdated,icon:item.icon,latitude:metadata?.latitude??null,longitude:metadata?.longitude??null};});} async getPrice(id:string){return (await this.getPrices()).find(x=>x.id===id);} }
export type ApiMarketDataResult = { prices: MarketPrice[]; source: 'government' | 'mock-fallback'; fallback: boolean; locationScope?: 'district' | 'state' | 'none'; location?: Record<string, unknown> };
export class ApiMarketDataProvider implements MarketDataProvider { async getPricesWithStatus(location?: UserLocation):Promise<ApiMarketDataResult> { const response=await getApiResponse<{ records?: unknown[]; source?: 'government' | 'mock-fallback'; fallback?: boolean; locationScope?: 'district' | 'state' | 'none'; location?: Record<string, unknown> }>('/api/market/prices', location ? { latitude: location.latitude, longitude: location.longitude, city: location.city, district: location.district ?? undefined, state: location.state } : undefined); if (__DEV__) console.info('[location] final location sent to market API', location); if(!response.data || !Array.isArray(response.data.records)) throw new Error('Backend returned an invalid market price response'); const fallback = response.data.fallback === true || response.fallback; return { prices: response.data.records as MarketPrice[], source: response.data.source === 'government' && !fallback ? 'government' : 'mock-fallback', fallback, locationScope: response.data.locationScope, location: response.data.location }; } async getPrices():Promise<MarketPrice[]> { return (await this.getPricesWithStatus()).prices; } async getPrice(id:string){return (await this.getPrices()).find(x=>x.id===id);} }
/** Backend-only placeholder. Government APIs/API keys must not be called or embedded in the mobile app. */
export class GovernmentMarketDataProvider implements MarketDataProvider { async getPrices():Promise<MarketPrice[]>{throw new Error('Government market data requires a backend adapter and secure API configuration.');} async getPrice(id:string){return (await this.getPrices()).find(x=>x.id===id);} }
