import { useState } from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { buyer, farmer, listings, notifications, orders, pooledLoads, prices, vehicle } from '@/data/mockData';
import { calculatePaymentSplit } from '@/services/paymentService';
import { formatINR } from '@/services/pricingService';
import { colors } from '@/theme/colors';
import { FEATURES } from '@/config/features';
import { AppHeader, BottomNavigation, Card, PrimaryButton, SearchBar, SectionHeader, SecondaryButton, StatCard, StatusBadge } from './ui';
import { OrderCard, PaymentSplitCard, PriceCard, ProductCard, QualityGradeCard, TransportCard } from './cards';
import { languages, useI18n } from '@/i18n';

const Page = ({ children, mode, active }: any) => <View style={s.root}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}>{children}</ScrollView>{mode ? <BottomNavigation mode={mode} active={active} navigate={router.push} /> : null}</View>;
export function Dashboard({ mode }: { mode: 'farmer'|'buyer' }) { const f = mode === 'farmer'; const person = f ? farmer : buyer; return <Page mode={mode} active="Home"><AppHeader title={`Good morning, ${f ? 'Arun' : 'Nila'}`} subtitle={person.location} /><View style={s.stats}><StatCard label={f ? "Today's market" : 'Available produce'} value={f ? '₹2,850' : '124 lots'} /><StatCard label={f ? 'Total earnings' : 'Active orders'} value={f ? farmer.earnings : buyer.activeOrders} accent={colors.amber} /></View><SectionHeader title="Quick actions" /><View style={s.actions}>{(f ? [['Scan quality','/farmer/scanner'],['List produce','/farmer/listing'],['Market prices','/farmer/marketplace'],['Logistics','/farmer/logistics']] : [['Browse produce','/buyer/marketplace'],['Market prices','/buyer/marketplace'],['My orders','/buyer/orders'],['Tracking','/buyer/tracking']]).map(([label,path]) => <SecondaryButton key={label} label={label} onPress={() => router.push(path as any)} />)}</View><SectionHeader title={f ? 'Today’s market signal' : 'Freshly listed'} action="View all" />{f ? <PriceCard item={prices[0]} /> : <ProductCard item={listings[0]} onPress={() => router.push('/buyer/product-details')} />}{FEATURES.notifications && <SecondaryButton label="View notifications" onPress={() => router.push(f ? '/farmer/notifications' : '/buyer/notifications')} />}</Page>; }
export function Market({ mode }: { mode: 'farmer'|'buyer' }) { const [search,setSearch]=useState(''); const items = mode === 'buyer' ? listings.filter(x => `${x.crop} ${x.farmer}`.toLowerCase().includes(search.toLowerCase())) : prices; return <Page mode={mode} active="Market"><AppHeader title={mode === 'buyer' ? 'Marketplace' : 'Market prices'} subtitle={mode === 'buyer' ? 'Verified, harvest-fresh lots' : 'Regional price intelligence · demo data'} />{mode === 'buyer' && <><SearchBar value={search} setValue={setSearch}/><View style={s.filters}><StatusBadge text="All crops"/><StatusBadge text="Grade A"/><StatusBadge text="Sort: latest"/></View></>}{items.map((item:any) => mode === 'buyer' ? <ProductCard key={item.id} item={item} onPress={() => router.push('/buyer/product-details')} /> : <PriceCard key={item.crop} item={item} />)}{mode === 'farmer' && FEATURES.directSelling && <PrimaryButton label="List produce" onPress={() => router.push('/farmer/listing')} />}</Page>; }
export function Orders({ mode }: { mode: 'farmer'|'buyer' }) { return <Page mode={mode} active="Orders"><AppHeader title="Orders" subtitle={mode === 'farmer' ? 'Manage fulfilment and pickup' : 'Your purchases and delivery status'} />{orders.map(x => <OrderCard key={x.id} item={x} onPress={() => router.push(mode === 'farmer' ? '/farmer/order-details' : '/buyer/order-details')} />)}<SecondaryButton label="View payment simulation" onPress={() => router.push(mode === 'farmer' ? '/farmer/payments' : '/buyer/payments')} /></Page>; }
export function OrderDetails({ mode }: { mode: 'farmer'|'buyer' }) { const f = mode === 'farmer'; return <Page mode={mode} active="Orders"><AppHeader title="Order AGN-2048" subtitle="Tomato · 500 kg · ₹14,250" /><Card><StatusBadge text="Vehicle Assigned"/><Text style={s.title}>{f ? 'New buyer order' : 'Order confirmed'}</Text><Text style={s.muted}>{f ? 'Nila Foods Pvt Ltd placed this verified order.' : 'Arun Kumar has prepared your produce for pickup.'}</Text></Card><TransportCard vehicle={vehicle}/><PrimaryButton label={f ? 'Mark produce ready' : 'Track shipment'} onPress={() => router.push(f ? '/farmer/logistics' : '/buyer/tracking')} /><SecondaryButton label="View payment" onPress={() => router.push(f ? '/farmer/payments' : '/buyer/payments')} /></Page>; }
export function Listing() { const [quantity,setQuantity]=useState('500'); const [price,setPrice]=useState('2850'); const [done,setDone]=useState(false); const estimated=(Number(quantity)||0)*(Number(price)||0)/100; return <Page mode="farmer" active="Market"><AppHeader title="List produce" subtitle="Create a verified lot" />{done ? <Card><Text style={s.title}>Listing published</Text><Text style={s.muted}>Your Tomato lot is now visible to verified buyers.</Text><PrimaryButton label="Back to dashboard" onPress={() => router.replace('/farmer/dashboard')} /></Card> : <><Field label="Crop" value="Tomato" editable={false}/><Field label="Quantity (kg)" value={quantity} setValue={setQuantity}/><Field label="Quality grade" value="Grade A" editable={false}/><Field label="Price (₹ / quintal)" value={price} setValue={setPrice}/><Field label="Harvest date" value="12 Sep 2026" editable={false}/><Field label="Location" value="Hosur, Tamil Nadu" editable={false}/><Field label="Description" value="Freshly harvested, sorted tomatoes" editable={false}/><Card><Text style={s.muted}>Estimated order value</Text><Text style={s.big}>{formatINR(estimated)}</Text></Card><PrimaryButton label="Publish listing" onPress={() => setDone(true)} /></>}</Page>; }
function Field({ label,value,setValue,editable=true }: any) { return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} editable={editable} onChangeText={setValue} keyboardType={label.includes('Quantity')||label.includes('Price')?'numeric':'default'} style={s.input}/></View>; }
export function Logistics() { return <Page mode="farmer" active="Orders"><AppHeader title="Logistics" subtitle="Shipment and load pooling" /><TransportCard vehicle={vehicle}/><Card><Text style={s.title}>Load pooling</Text><Text style={s.muted}>Combine nearby loads for a more efficient pickup.</Text>{pooledLoads.map(x=><View key={x.name} style={s.row}><Text style={s.muted}>{x.name}</Text><Text style={s.bold}>{x.quantity}</Text></View>)}<Text style={s.big}>1,250 kg</Text><StatusBadge text="38% projected fuel saving · demo"/></Card><PrimaryButton label="View order details" onPress={() => router.push('/farmer/order-details')} /></Page>; }
export function Tracking() { return <Page mode="buyer" active="Tracking"><AppHeader title="Shipment tracking" subtitle="Order AGN-2048" /><TransportCard vehicle={vehicle}/><Card><Text style={s.title}>Route progress</Text>{['Pickup confirmed','Vehicle assigned','In transit','Delivered'].map((x,i)=><View key={x} style={s.timeline}><View style={[s.dot,i<2&&s.dotActive]}/><Text style={s.muted}>{x}{i===1 ? ' · ETA 42 minutes' : ''}</Text></View>)}</Card><PrimaryButton label="Open payment" onPress={() => router.push('/buyer/payments')} /></Page>; }
export function Payments({ mode }: { mode: 'farmer'|'buyer' }) { const total=50000; return <Page mode={mode} active="Orders"><AppHeader title="Payment split" subtitle="Demo / simulation only — no real payment is processed" /><PaymentSplitCard total={total} split={calculatePaymentSplit(total)} /><SecondaryButton label="Back to orders" onPress={() => router.push(mode === 'farmer' ? '/farmer/orders' : '/buyer/orders')} /></Page>; }
export function Notifications({ mode }: { mode: 'farmer'|'buyer' }) { return <Page mode={mode} active="Home"><AppHeader title="Notifications" subtitle="Updates from your supply chain" />{notifications.map((n,i)=><Card key={n}><Text style={s.note}>{i<2?'ORDER UPDATE':'MARKET UPDATE'}</Text><Text style={s.muted}>{n}</Text></Card>)}</Page>; }
export function Profile({ mode }: { mode: 'farmer'|'buyer' }) { const p=mode==='farmer'?farmer:buyer; const { language, setLanguage, t } = useI18n(); return <Page mode={mode} active="Profile"><AppHeader title={t('profile')} subtitle="Verified account" /><Card><Text style={s.title}>{p.name}</Text><StatusBadge text="Verified"/><Text style={s.muted}>{p.location}</Text><Text style={s.muted}>{mode==='farmer'?`${farmer.farmSize} · ${farmer.crops}`:`Total purchases ${buyer.purchases} · Active orders ${buyer.activeOrders}`}</Text><Text style={s.muted}>Rating {p.rating} / 5</Text></Card>{mode==='farmer'&&<Card><Text style={s.title}>{t('language')}</Text><Text style={s.muted}>{t('chooseLanguage')}</Text><View style={s.languageGrid}>{languages.map(option=>{const selected=language===option.code;return <Pressable key={option.code} onPress={()=>setLanguage(option.code)} style={[s.languageOption,selected&&s.languageSelected]}><Text style={[s.languageText,selected&&s.languageTextSelected]}>{option.label}</Text></Pressable>})}</View></Card>}<SecondaryButton label="Switch role" onPress={() => router.push('/settings/role-switch')} /></Page>; }
export function ProductDetails() { const item=listings[0]; return <Page mode="buyer" active="Market"><AppHeader title="Tomato" subtitle="Premium verified lot" /><QualityGradeCard/><Card><Text style={s.title}>{item.quantity} available</Text><Text style={s.big}>{formatINR(item.price)} <Text style={s.unit}>/ quintal</Text></Text><Text style={s.muted}>Farmer: {item.farmer} · {item.location}</Text><Text style={s.muted}>Harvested: {item.harvestDate}</Text><Text style={s.muted}>{item.description}</Text><StatusBadge text="Verified farmer"/></Card><PrimaryButton label="Place order" onPress={() => router.push('/buyer/checkout')} /></Page>; }
export function Checkout() { const [confirmed,setConfirmed]=useState(false); return <Page mode="buyer" active="Orders"><AppHeader title={confirmed?'Order confirmed':'Checkout'} subtitle="Tomato · Grade A · 500 kg" />{confirmed?<Card><Text style={s.title}>Order AGN-2048 confirmed</Text><Text style={s.muted}>The farmer has been notified. You can follow the shipment from tracking.</Text><PrimaryButton label="Track order" onPress={()=>router.replace('/buyer/tracking')}/></Card>:<><Card><Text style={s.title}>Order summary</Text><Text style={s.muted}>500 kg Tomato · ₹2,850 / quintal</Text><Text style={s.big}>₹14,250</Text></Card><PrimaryButton label="Confirm demo order" onPress={()=>setConfirmed(true)}/><Text style={s.note}>No payment will be collected in this demo.</Text></>}</Page>; }
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.cream},page:{padding:18,gap:16,paddingBottom:28},stats:{flexDirection:'row',gap:12},actions:{gap:10},filters:{flexDirection:'row',gap:8,flexWrap:'wrap'},title:{fontSize:19,fontWeight:'800',color:colors.ink},big:{fontSize:26,fontWeight:'900',color:colors.green},muted:{color:colors.muted,lineHeight:20},note:{fontSize:12,color:colors.muted,textAlign:'center'},field:{gap:6},label:{fontSize:13,fontWeight:'700',color:colors.ink},input:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:13,color:colors.ink},row:{flexDirection:'row',justifyContent:'space-between'},bold:{fontWeight:'800',color:colors.ink},timeline:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:8},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.line},dotActive:{backgroundColor:colors.green},unit:{fontSize:13,color:colors.muted},languageGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},languageOption:{borderWidth:1,borderColor:colors.line,borderRadius:10,paddingHorizontal:11,paddingVertical:8},languageSelected:{backgroundColor:colors.mint,borderColor:colors.green},languageText:{fontSize:12,fontWeight:'700',color:colors.muted},languageTextSelected:{color:colors.green}});
