import { ReactNode } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SymbolView } from 'expo-symbols';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors } from '@/theme/colors';
import { spacing } from '@/theme/spacing';
import { useI18n } from '@/i18n';

export const Card = ({ children, style }: { children: ReactNode; style?: object }) => <View style={[styles.card, style]}>{children}</View>;
export const PrimaryButton = ({ label, onPress }: { label: string; onPress: () => void }) => <Pressable onPress={onPress} style={styles.primary}><Text style={styles.primaryText}>{label}</Text></Pressable>;
export const SecondaryButton = ({ label, onPress }: { label: string; onPress: () => void }) => <Pressable onPress={onPress} style={styles.secondary}><Text style={styles.secondaryText}>{label}</Text></Pressable>;
export const AppHeader = ({ title, subtitle }: { title: string; subtitle?: string }) => <View style={styles.header}><Text style={styles.headerTitle}>{title}</Text>{subtitle ? <Text style={styles.muted}>{subtitle}</Text> : null}</View>;
export const SectionHeader = ({ title, action }: { title: string; action?: string }) => <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{action ? <Text style={styles.action}>{action}</Text> : null}</View>;
export const StatusBadge = ({ text }: { text: string }) => <View style={styles.badge}><Text style={styles.badgeText}>{text}</Text></View>;
export const SearchBar = ({ value, setValue }: { value: string; setValue: (value: string) => void }) => <TextInput value={value} onChangeText={setValue} placeholder="Search crop or farmer" placeholderTextColor={colors.muted} style={styles.search} />;
export const EmptyState = ({ label }: { label: string }) => <Card><Text style={styles.muted}>{label}</Text></Card>;
export const StatCard = ({ label, value, accent = colors.green }: { label: string; value: string; accent?: string }) => <Card style={{ flex: 1, borderTopWidth: 3, borderTopColor: accent }}><Text style={styles.muted}>{label}</Text><Text style={styles.stat}>{value}</Text></Card>;
export function AppIcon({ name, size = 22, color = colors.green }: { name: any; size?: number; color?: string }) { return <SymbolView name={name} size={size} tintColor={color} />; }

const cropTones: Record<string, { background: string; color: string; symbol: any }> = {
  Tomato: { background: '#FCE8E5', color: '#C94C40', symbol: { ios: 'leaf.fill', android: 'nutrition', web: 'nutrition' } },
  Onion: { background: '#F4EAFB', color: '#8C55A8', symbol: { ios: 'leaf.fill', android: 'nutrition', web: 'nutrition' } },
  Potato: { background: '#F5ECDC', color: '#A36A35', symbol: { ios: 'leaf.fill', android: 'nutrition', web: 'nutrition' } },
  Chilli: { background: '#FDE8E7', color: '#C8413A', symbol: { ios: 'flame.fill', android: 'local_fire_department', web: 'local_fire_department' } },
  Turmeric: { background: '#FFF4D6', color: '#B98616', symbol: { ios: 'sun.max.fill', android: 'wb_sunny', web: 'wb_sunny' } },
  Cotton: { background: '#EEF3F0', color: '#66857A', symbol: { ios: 'cloud.fill', android: 'cloud', web: 'cloud' } },
};
export function CropVisual({ crop, size = 44 }: { crop: string; size?: number }) { const tone = cropTones[crop] ?? { background: colors.mint, color: colors.green, symbol: { ios: 'leaf.fill', android: 'eco', web: 'eco' } }; return <View accessibilityLabel={`${crop} crop image`} style={[styles.cropVisual, { width: size, height: size, borderRadius: size * .32, backgroundColor: tone.background }]}><AppIcon name={tone.symbol} size={Math.round(size * .52)} color={tone.color} /></View>; }

export const BottomNavigation = ({ mode, active, navigate }: { mode: 'farmer'|'buyer'; active: string; navigate: (path: any) => void }) => { const insets = useSafeAreaInsets(); const { t } = useI18n(); const farmerItems: [string, string, any, 'home'|'market'|'scanner'|'orders'|'profile'][] = [['Home','/farmer/dashboard',{ ios: 'house.fill', android: 'home', web: 'home' },'home'],['Market','/farmer/marketplace',{ ios: 'chart.line.uptrend.xyaxis', android: 'show_chart', web: 'show_chart' },'market'],['Scanner','/farmer/scanner',{ ios: 'viewfinder', android: 'center_focus_strong', web: 'center_focus_strong' },'scanner'],['Orders','/farmer/orders',{ ios: 'shippingbox.fill', android: 'inventory_2', web: 'inventory_2' },'orders'],['Profile','/farmer/profile',{ ios: 'person.crop.circle', android: 'account_circle', web: 'account_circle' },'profile']]; const buyerItems: [string, string, any, 'home'|'market'|'orders'|'tracking'|'profile'][] = [['Home','/buyer/dashboard',{ ios: 'house.fill', android: 'home', web: 'home' },'home'],['Market','/buyer/marketplace',{ ios: 'bag.fill', android: 'storefront', web: 'storefront' },'market'],['Orders','/buyer/orders',{ ios: 'shippingbox.fill', android: 'inventory_2', web: 'inventory_2' },'orders'],['Tracking','/buyer/tracking',{ ios: 'location.fill', android: 'location_on', web: 'location_on' },'tracking'],['Profile','/buyer/profile',{ ios: 'person.crop.circle', android: 'account_circle', web: 'account_circle' },'profile']]; const items = mode === 'farmer' ? farmerItems : buyerItems; return <View style={[styles.nav, { paddingBottom: Math.max(insets.bottom, 10) }]}>{items.map(([label,path,icon,key]) => { const selected = active === label; return <Pressable key={label} accessibilityRole="tab" accessibilityState={{ selected }} onPress={() => navigate(path)} style={styles.navItem}><View style={[styles.navIcon, selected && styles.navIconActive]}><AppIcon name={icon} size={20} color={selected ? colors.green : colors.muted} /></View><Text numberOfLines={1} style={[styles.navText, selected && styles.navActive]}>{t(key)}</Text></Pressable>})}</View>; };
const styles = StyleSheet.create({ card: { backgroundColor: colors.card, padding: spacing.md, borderRadius: 18, gap: 6, boxShadow: '0 3px 12px rgba(17, 57, 32, 0.08)', elevation: 2 }, primary: { padding: 16, alignItems: 'center', backgroundColor: colors.green, borderRadius: 14 }, primaryText: { color: 'white', fontWeight: '800' }, secondary: { padding: 14, alignItems: 'center', borderWidth: 1, borderColor: colors.green, borderRadius: 14 }, secondaryText: { color: colors.green, fontWeight: '800' }, header: { gap: 4 }, headerTitle: { fontSize: 28, fontWeight: '800', color: colors.ink }, muted: { color: colors.muted, fontSize: 14 }, section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sectionTitle: { fontSize: 19, fontWeight: '800', color: colors.ink }, action: { color: colors.green, fontWeight: '700' }, badge: { alignSelf: 'flex-start', backgroundColor: colors.mint, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 99 }, badgeText: { color: colors.green, fontSize: 11, fontWeight: '800' }, search: { backgroundColor: colors.card, borderRadius: 14, paddingHorizontal: 15, paddingVertical: 14, color: colors.ink, boxShadow: '0 2px 8px rgba(17,57,32,.06)' }, stat: { color: colors.ink, fontSize: 21, fontWeight: '800', marginTop: 4 }, cropVisual: { alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, nav: { flexDirection: 'row', backgroundColor: colors.card, borderTopWidth: 1, borderColor: colors.line, paddingTop: 8, justifyContent: 'space-around', elevation: 10, boxShadow: '0 -4px 16px rgba(17,57,32,.06)' }, navItem: { flex: 1, alignItems: 'center', gap: 2, minWidth: 0 }, navIcon: { width: 34, height: 29, alignItems: 'center', justifyContent: 'center', borderRadius: 12 }, navIconActive: { backgroundColor: colors.mint }, navText: { fontSize: 10, color: colors.muted, fontWeight: '700' }, navActive: { color: colors.green } });
